// Mocks generated by Mockito 5.4.0 from annotations
// in booqs_mobile/test/unit/answer_reward_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:booqs_mobile/utils/app_review_service.dart' as _i5;
import 'package:booqs_mobile/utils/dialogs.dart' as _i2;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Dialogs].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogs extends _i1.Mock implements _i2.Dialogs {
  MockDialogs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reward(_i4.Widget? screen) => (super.noSuchMethod(
        Invocation.method(
          #reward,
          [screen],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AppReviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppReviewService extends _i1.Mock implements _i5.AppReviewService {
  MockAppReviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> request() => (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
