import 'package:booqs_mobile/models/word.dart';

class WordBuilder {
  static Word build({
    int? id,
    int? dictionaryId,
    int? sentenceId,
    int? posTagId,
    String? entry,
    int? langNumberOfEntry,
    String? entrySsml,
    String? meaning,
    String? meaningJa,
    String? meaningEn,
    int? langNumberOfMeaning,
    String? explanation,
    String? meaningImageUrl,
    String? pos,
    String? ipa,
    String? reading,
    String? etymologies,
    String? synonyms,
    String? antonyms,
    String? related,
    String? sensesJson,
    List? sensesTags,
    List? formsList,
    int? wordRequestsCount,
    int? acceptedWordRequestsCount,
    int? pendingWordRequestsCount,
  }) {
    return Word(
      id: id ?? 1,
      dictionaryId: dictionaryId ?? 1,
      sentenceId: sentenceId,
      posTagId: posTagId,
      entry: entry ?? 'test',
      langNumberOfEntry: langNumberOfEntry ?? 0,
      entrySsml: entrySsml,
      meaning: meaning ?? 'テスト',
      meaningJa: meaningJa,
      meaningEn: meaningEn,
      langNumberOfMeaning: langNumberOfMeaning ?? 1,
      explanation: explanation ?? '',
      meaningImageUrl: meaningImageUrl,
      pos: pos,
      ipa: ipa,
      reading: reading,
      etymologies: etymologies,
      synonyms: synonyms,
      antonyms: antonyms,
      related: related,
      sensesJson: sensesJson,
      sensesTags: sensesTags,
      formsList: formsList,
      wordRequestsCount: wordRequestsCount ?? 0,
      acceptedWordRequestsCount: acceptedWordRequestsCount ?? 0,
      pendingWordRequestsCount: pendingWordRequestsCount ?? 0,
    );
  }
}
